### ISSUE TITLE
Indented sections are undetected

### ISSUE THREAD

**Issue by amrhassan** [Jumpscale/python-consistent-toml#10]
In the following TOML sample, the [handlers.env] block is completely undetected:
```toml
[main]
listen = ":8966"
redis_host =  "localhost:6379"
redis_password = ""

[influxdb]
host = "localhost:8086"
db   = "agentcontroller"
user = "ac"
password = "acctrl"

[handlers]
binary = "python2.7"
cwd = "./handlers"
    [handlers.env]
    PYTHONPATH = "/opt/jumpscale7/lib:../client"
    SYNCTHING_URL = "http://localhost:8384/"
    SYNCTHING_SHARED_FOLDER_ID = "jumpscripts"
    #SYNCTHING_API_KEY = ""
    REDIS_ADDRESS = "localhost"
    REDIS_PORT = "6379"
    #REDIS_PASSWORD = ""
```

It parses to the object:
```python
{'handlers': {'binary': 'python2.7',
  'cwd': './handlers',
  'env': {'PYTHONPATH': '/opt/jumpscale7/lib:../client',
   'SYNCTHING_SHARED_FOLDER_ID': 'jumpscripts',
   'SYNCTHING_URL': 'http://localhost:8384/'}},
 'influxdb': {'db': 'agentcontroller',
  'host': 'localhost:8086',
  'password': 'acctrl',
  'user': 'ac'},
 'main': {'listen': ':8966',
  'redis_host': 'localhost:6379',
  'redis_password': ''}}
```

**Comment by muhamadazmy** [comment]
Also loading this file crashes with an exception

```toml
[main]
gid = 1
nid = 10
max_jobs = 100
message_id_file = "./.mid"
history_file = "./.history"
agent_controllers = ["http://localhost:8966/"]

[cmds]
    [cmds.execute_js_py]
    binary = "python2.7"
    cwd = "./jumpscripts"
    script = "{domain}/{name}.py"

    [cmds.sync]
    #syncthing extension
    binary = "python2.7"
    cwd = "./extensions/sync"
    script = "{name}.py"
    [cmds.sync.env]
    PYTHONPATH = "../"
    JUMPSCRIPTS_HOME = "../../jumpscripts"
    SYNCTHING_URL = "http://localhost:8384"

[channel]
cmds = [0] # long polling from agent 0

[logging]
    [logging.db]
    type = "DB"
    log_dir = "./logs"
    levels = [2, 4, 7, 8, 9]  # (all error messages) empty for all

    [logging.ac]
    type = "AC"
    flush_int = 300 # seconds (5min)
    batch_size = 1000 # max batch size, force flush if reached this count.
    agent_controllers = [] # to all agents
    levels = [2, 4, 7, 8, 9]  # (all error messages) empty for all

    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

[stats]
interval = 60 # seconds
agent_controllers = []
```
