### ISSUE TITLE
Can't access dict at 3rd level 

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/python-consistent-toml#16]
Is there a limit on how deep I can nest my dictionaries 
In this snippet
```toml
[cmds]
    [cmds.sync]
    #syncthing extension
    binary = "python2.7"
    cwd = "./extensions/sync"
    script = "{name}.py"
        [cmds.sync.env]
        PYTHONPATH = "../"
        JUMPSCRIPTS_HOME = "../../jumpscripts"
        SYNCTHING_URL = "http://localhost:8384"
```
I can't read or set value of SYNCTHING_URL (for example)
