### ISSUE TITLE
String representation of module data structures should be more human-readable

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/python-consistent-toml#17]
I expect the toml structure to `repr()` nicely in ipython for ease of inspection of values
Considering this snippet
```toml
[cmds]
    [cmds.sync]
    #syncthing extension
    binary = "python2.7"
    cwd = "./extensions/sync"
    script = "{name}.py"
        [cmds.sync.env]
        PYTHONPATH = "../"
        JUMPSCRIPTS_HOME = "../../jumpscripts"
        SYNCTHING_URL = "http://localhost:8384"
```

in ipython
```python
cfg = contoml.load(...)
In [17]: cfg
Out[17]: <contoml.file.file.TOMLFile instance at 0x7f8419bd6d40>

In [18]: cfg['cmds']
Out[18]: <contoml.file.cascadedict.CascadeDict instance at 0x7f8419b95cb0>

In [19]: cfg['cmds']['sync']
Out[19]: 
[[93-whitespace:  , 93-whitespace:  , 93-whitespace:  , 93-whitespace:  ], [95-comment: #syncthing extension, 91-newline: 
], [93-whitespace:  , 93-whitespace:  , 93-whitespace:  , 93-whitespace:  ], [50-bare_string: binary], [93-whitespace:  ], [0-assignment: =], [93-whitespace:  ], [90-string: "python2.7"], [], [91-newline: 
], [93-whitespace:  , 93-whitespace:  , 93-whitespace:  , 93-whitespace:  ], [50-bare_string: cwd], [93-whitespace:  ], [0-assignment: =], [93-whitespace:  ], [90-string: "./extensions/sync"], [], [91-newline: 
], [93-whitespace:  , 93-whitespace:  , 93-whitespace:  , 93-whitespace:  ], [50-bare_string: script], [93-whitespace:  ], [0-assignment: =], [93-whitespace:  ], [90-string: "{name}.py"], [], [91-newline: 
]]
```

This is totally not readable, IMHO it should represent the actual values loaded, not just print the lexcal structures or the module name.
