### ISSUE TITLE
can't prettify toml

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/python-consistent-toml#18]
Starting from that file
```toml
[main]
gid = 1
nid = 1
max_jobs = 100
message_id_file = "./.mid"
history_file = "./.history"
roles = ["agent"]
include = "./conf"

[controllers]
    [controllers.main]
    url = "https://dev2/controller/"
        [controllers.main.security]
        client_certificate = "/opt/jumpscale7/hrd/apps/agent2__node1/client_node1.crt"
        client_certificate_key = "/opt/jumpscale7/hrd/apps/agent2__node1/client_node1.key"
        certificate_authority = "/opt/jumpscale7/hrd/apps/agent2__node1/server.crt"
      
[channel]
cmds = [] # empty for long polling from all defined controllers, or specif controllers keys

[extensions]
    #the very basic agent extensions. Also please check the toml files under
    #the Main.Include folder for more extensions
    [extensions.syncthing]
    binary = "./syncthing"
    cwd = "./extensions/syncthing"
    args = ["-home", "./home", "-gui-address", "127.0.0.1:28384"]

    [extensions.sync]
    #syncthing extension
    binary = "python2.7"
    cwd = "./extensions/sync"
    args = ["{name}.py"]
        [extensions.sync.env]
        PYTHONPATH = "../:/opt/jumpscale7/lib"
        JUMPSCRIPTS_HOME = "/opt/jumpscale7/apps/agent2/jumpscripts/"
        SYNCTHING_URL = "http://localhost:28384"

    [extensions.jumpscript]
    binary = "python2.7"
    cwd = "./extensions/jumpscript"
    args = ["wrapper.py", "modern", "{domain}", "{name}"]
        [extensions.jumpscript.env]
        SOCKET = "/tmp/jumpscript.sock"
        PYTHONPATH = "../"

    [extensions.legacy]
    binary = "python2.7"
    cwd = "./extensions/jumpscript"
    args = ["wrapper.py", "legacy", "{domain}", "{name}"]
        [extensions.legacy.env]
        PYTHONPATH = "../" # for utils
        SOCKET = "/tmp/jumpscript.sock"

    [extensions.js_daemon]
    binary = "python2.7"
    cwd = "./extensions/jumpscript"
    args = ["executor.py"]
        [extensions.js_daemon.env]
        SOCKET = "/tmp/jumpscript.sock"
        PYTHONPATH = "../:/opt/jumpscale7/lib"
        JUMPSCRIPTS_HOME = "/opt/jumpscale7/apps/agent2/jumpscripts/"
        JUMPSCRIPTS_LEGACY_HOME = "/opt/jumpscale7/apps/agent2/legacy/"

[logging]
    [logging.db]
    type = "DB"
    log_dir = "./logs"
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.ac]
    type = "AC"
    flush_int = 300 # seconds (5min)
    batch_size = 1000 # max batch size, force flush if reached this count.
    controllers = [] # empty for all controllers, or controllers keys
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

[stats]
interval = 60 # seconds
controllers = [] # empty for all controllers, or controllers keys

[hubble]
controllers = [] # accept forwarding commands and connections from all controllers. Or specific controllers by name

[startup]
    [startup.syncthing]
    name = "syncthing"
        [startup.syncthing.args]
        loglevels_db = '*'
        domain = "agent"
        name = "syncthing"

    [startup.legacy]
    name = "js_legacy_daemon"
        [startup.legacy.args]
        max_restart = 10
        domain = "agent"
        name = "legacy"

    [startup.jumpscript]
    name = "js_daemon"
        [startup.jumpscript.args]
        max_restart = 10
        domain = "agent"
        name = "jumpscript"
```
I had some more content to it
```python
        cfg_path = 'agent2.toml'
        cfg = contoml.load(cfg_path)
        cfg['extensions']['redis'] = {
            'binary': './redis-server',
            'cwd': '/opt/jumpscale7/apps/redis',
            'args': ['/opt/jumpscale7/var/redis/ovh4/redis.conf']
        }
        cfg['startup']['redis'] = {
            'name': 'redis',
            'args': {
                'max_restart': 1,
                'domain': 'jumpscale',
                'name': 'redis',
            }
        }
        contoml.dump(cfg, cfg_path, prettify=True)
```

Result is this error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/bin/js in <module>()
----> 1 contoml.dump(cfg, 'agent2.toml', prettify=True)

/opt/jumpscale7/lib/contoml/__init__.pyc in dump(obj, file_path, prettify)
     73     """
     74     with open(file_path, 'w') as fp:
---> 75         fp.write(dumps(obj, prettify=prettify))

/opt/jumpscale7/lib/contoml/__init__.pyc in dumps(value, prettify)
     45     if isinstance(value, TOMLFile):
     46         if prettify:
---> 47             value.prettify()
     48         return value.dumps()
     49 

/opt/jumpscale7/lib/contoml/file/file.pyc in prettify(self, prettifiers)
    177         Reformats this TOML file using the specified consistent set of formatting rules.
    178         """
--> 179         prettifier.prettify(self, prettifiers)
    180         self._recreate_navigable()
    181 

/opt/jumpscale7/lib/contoml/prettifier/__init__.pyc in prettify(toml_file, prettifiers)
     35     """
     36     for prettifier in prettifiers:
---> 37         prettifier(toml_file)

/opt/jumpscale7/lib/contoml/prettifier/linelength.pyc in line_lingth_limiter(toml_file)
     20     for (i, element) in enumerate(toml_file.elements):
     21         if isinstance(element, TableElement):
---> 22             new_tables = _do_table(element.sub_elements)
     23             if i > 0 and new_tables:
     24                 table_names = toml_file.elements[i-1].names if i > 0 else tuple()

/opt/jumpscale7/lib/contoml/prettifier/linelength.pyc in _do_table(table_elements)
     59         if line_length() > MAXIMUM_LINE_LENGTH:
     60             value_i = next_value()
---> 61             value = table_elements[value_i]
     62 
     63             if isinstance(value, AtomicElement) and isinstance(value.value, six.string_types):

TypeError: list indices must be integers, not float

```
