### ISSUE TITLE
Dict inside dict issue

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/python-consistent-toml#20]
code that create the toml
```python
        cfg = contoml.new()
        cfg['Gobal'] = {'Debug': False}
        cfg['Fuse'] = {
            'nVdisksRoot': vdiskroot,
            'CifsRoot': cifspath,
            'Refresh': refresh,
            'BlockSize': blockSize,
            'Timeout': timeout,
        }
        cfg['Arakoon'] = {
            'ClientID': arakoonHRD.getStr('instance.clusterid'),
            'ClusterID': arakoonHRD.getStr('instance.clusterid')
        }

        for node in arakoon:
            item = arakoonHRD.get("instance." + node)
            cfg['Arakoon']['Nodes'] = {
                node: {
                    'ID': node,
                    'Host': item['ip'],
                    'Port': item['client_port']
                }
            }
```

result
```toml
[Gobal]
Debug = false

[Fuse]
BlockSize = 16777216
Timeout = 10
nVdisksRoot = "/mnt/vdisks/"
Refresh = 20
CifsRoot = "/storage/vnas"

[Arakoon]
ClusterID = "vnas"
ClientID = "vnas"
Nodes = {master = {Host = "172.20.0.12", ID = "master", Port = "7080"}}

```

expected :
```toml
[Global]
  Debug = true

[Fuse]
  VDisksRoot = "/mnt/vdisks"
  CifsRoot = "/storage/vnas"
  Refresh = 20
  Timeout = 10
  BlockSize = 64

[Arakoon]
  ClientID = "vnas"
  ClusterID = "vnas"
  [Arakoon.Nodes]
    [Arakoon.Nodes.master]
      ID = "master"
      Host = "dev2"
      Port = 7080
```

error when readed with the official go implementation of the toml
```
2015/10/12 16:38:47 Unable to open config file (config.toml) : Near line 14, key 'Arakoon.Nodes': Near line 14: Expected value but found '{' instead.
```

go struct used
```go
type global struct {
	Debug bool
}

type fuse struct {
	VDisksRoot string //Path of the directory containing all mounted vdisks
	CifsRoot   string //Path of the fuselayer

	Refresh   time.Duration //How often update disks status
	Timeout   time.Duration //Allowed duration of a disk check
	BlockSize uint          //Max block size of the fuse layer
}

type arakoon struct {
	ClientID  string
	ClusterID string //arakoon
	Nodes     map[string]grakoon.Node
}

type Config struct {
	Global global

	Fuse fuse

	Arakoon arakoon
}
```
