### ISSUE TITLE
Should not construct a multiline string within an inline table

### ISSUE THREAD

**Issue by amrhassan** [Jumpscale/python-consistent-toml#21]
Modifying a TOML file can lead to creating a multiline string within an inline table (#19).

Example:
```python
toml = '/opt/jumpscale7/apps/agentcontroller2/agentcontroller2.toml'
cfg = contoml.load(toml)
cfg.array('listen')[0]['tls'] = {'cert': cert, 'key': key}
cfg.array('listen')[0]['clientCA'] = {'cert': ca}
```

Leads to the following TOML file which fails to parse using the Go parser.

```toml
[main]
redis_host =  "127.0.0.1"
redis_password = ""

#Default http
[[listen]]
  Address = ":8966"
  tls = {cert = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/cert.pem\
""", key = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/key.pem\
"""}
  clientCA = {cert = """
/opt/code/github/jumpscale/ays2/services/agentcontroller2!main/tls/ca.pem\
"""}

#Example for https with multiple virtual hosts and clientcertificates
#[[listen]]
#  Address = ":8443"
#  [[listen.tls]]
#    cert = "/path/to/domain1_certificate.cert"
#    key = "/path/to/domain1_keyfile.key"
#  [[listen.tls]]
#    cert = "/path/to/domain2_certificate.cert"
#    key = "/path/to/domain2_keyfile.key"
#  [[listen.clientCA]]
#    cert = "/path/to/CAcert1.cert"
#  [[listen.clientCA]]
#    cert = "/path/to/CAcert2.cert"

[influxdb]
host = "127.0.0.1:8086"
db   = "main"
user = "root"
password = "root"

[handlers]
binary = "python2.7"
cwd = "./handlers"
    [handlers.env]
    PYTHONPATH = "/opt/jumpscale7/lib"
    HOME = "/root"
    SYNCTHING_URL = "http://localhost:18384/"
    #SYNCTHING_API_KEY = ""
    REDIS_ADDRESS = "127.0.0.1"
    REDIS_PORT = ""
    REDIS_PASSWORD = ""
    #REDIS_PASSWORD = ""

##### The following 2 sections are supportive for syncthing operation
##### Please don't remove or edit unless you know what you are doing
##### This will get replace once we implement local transport for hubbble.
[syncthing]
port=9066

[[listen]]
address="127.0.0.1:9066"
##### END SECTION.
```
