### ISSUE TITLE
Empty lists are not supported

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/python-consistent-toml#4]
When loading a toml file that has something like

```toml
[section]
key = []
```
It fails on the empty list. Putting any value between the brackets make it pass.
